spring.application.name=playground
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XE
spring.datasource.username=C##app_user
spring.datasource.password=p1aygr0und
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
