spring.application.name=playground
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521/XEPDB1}
spring.datasource.username=PLAY
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:GROUND}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.whs3.playground=DEBUG