ALTER SESSION SET CONTAINER = XEPDB1;

CREATE PLUGGABLE DATABASE XEPDB1 ADMIN USER pdbadmin IDENTIFIED BY password
    FILE_NAME_CONVERT=('/opt/oracle/oradata/XE/pdbseed/', '/opt/oracle/oradata/XE/XEPDB1/')
    DEFAULT TABLESPACE USERS DATAFILE '/opt/oracle/oradata/XE/XEPDB1/users01.dbf' SIZE 1G AUTOEXTEND ON NEXT 128M MAXSIZE UNLIMITED;

ALTER PLUGGABLE DATABASE XEPDB1 OPEN;

ALTER SESSION SET CONTAINER = XEPDB1;


CREATE USER PLAY IDENTIFIED BY GROUND;
GRANT CONNECT, RESOURCE, DBA TO PLAY;
ALTER USER PLAY QUOTA UNLIMITED ON USERS;

-- 테이블 생성
CREATE TABLE PLAY.USERS (
                            USERNUM NUMBER PRIMARY KEY,
                            USERID VARCHAR2(50) UNIQUE NOT NULL,
                            USERPW VARCHAR2(50) NOT NULL,
                            ROLE VARCHAR2(10) DEFAULT 'USER' NOT NULL
);

-- 시퀀스 생성
CREATE SEQUENCE PLAY.USER_SEQ START WITH 1 INCREMENT BY 1;

-- 게시판 테이블 생성
CREATE TABLE PLAY.BOARD (
                            ID NUMBER PRIMARY KEY,
                            TITLE VARCHAR2(100) NOT NULL,
                            CONTENT VARCHAR2(4000),
                            AUTHOR VARCHAR2(50) NOT NULL,
                            CREATEDAT DATE DEFAULT SYSDATE,
                            MODIFIEDAT DATE DEFAULT SYSDATE
);

CREATE SEQUENCE PLAY.BOARD_SEQ START WITH 1 INCREMENT BY 1;

-- 회원/관리자 계정 데이터 삽입
INSERT INTO PLAY.USERS (USERNUM, USERID, USERPW, ROLE) VALUES (PLAY.USER_SEQ.nextval, 'admin', 'admin', 'ADMIN');
INSERT INTO PLAY.USERS (USERNUM, USERID, USERPW, ROLE) VALUES (PLAY.USER_SEQ.NEXTVAL, 'bizUser01', 'b1z', 'BUSINESS');

--게시판 데이터 삽입
INSERT INTO PLAY.BOARD (ID, TITLE, CONTENT, AUTHOR, CREATEDAT, MODIFIEDAT) VALUES (PLAY.BOARD_SEQ.nextval, '기업회원 전용 자료 안내', '내용 생략', 'admin', SYSDATE, SYSDATE);

INSERT INTO PLAY.BOARD (ID, TITLE, CONTENT, AUTHOR, CREATEDAT, MODIFIEDAT)
VALUES (PLAY.BOARD_SEQ.NEXTVAL, '기업회원 전용 자료 안내', '첨부된 파일을 확인해주세요. (내용 생략)', 'bizUser01', SYSDATE, SYSDATE);