CREATE PLUGGABLE DATABASE XEPDB1 ADMIN USER pdbadmin IDENTIFIED BY password
    FILE_NAME_CONVERT=('/opt/oracle/oradata/XE/pdbseed/', '/opt/oracle/oradata/XE/XEPDB1/')
    DEFAULT TABLESPACE USERS DATAFILE '/opt/oracle/oradata/XE/XEPDB1/users01.dbf' SIZE 1G AUTOEXTEND ON NEXT 128M MAXSIZE UNLIMITED;

ALTER PLUGGABLE DATABASE XEPDB1 OPEN;

ALTER SESSION SET CONTAINER = XEPDB1;


CREATE USER PLAY IDENTIFIED BY GROUND;
GRANT CONNECT, RESOURCE, DBA TO PLAY;
ALTER USER PLAY QUOTA UNLIMITED ON USERS;

-- 테이블 생성
CREATE TABLE PLAY.USERS (
                            USERNUM NUMBER PRIMARY KEY,
                            USERID VARCHAR2(50) UNIQUE NOT NULL,
                            USERPW VARCHAR2(50) NOT NULL,
                            ROLE VARCHAR2(10) DEFAULT 'USER' NOT NULL
);

-- 시퀀스 생성
CREATE SEQUENCE PLAY.USER_SEQ START WITH 1 INCREMENT BY 1;

-- 게시판 테이블 생성
CREATE TABLE PLAY.BOARD (
                            ID NUMBER PRIMARY KEY,
                            TITLE VARCHAR2(100) NOT NULL,
                            CONTENT VARCHAR2(4000),
                            AUTHOR VARCHAR2(50) NOT NULL,
                            CREATEDAT DATE DEFAULT SYSDATE,
                            MODIFIEDAT DATE DEFAULT SYSDATE
);

CREATE SEQUENCE PLAY.BOARD_SEQ START WITH 1 INCREMENT BY 1;
